import requests
from bs4 import BeautifulSoup
import time
import json
import urllib.parse

genius_client_id     = 'INSERT CLIENT ID '
genius_client_secret = 'INSERT CLIENT SECRET'
genius_access_token  = 'INSERT ACCESS TOKEN'

base_url = "https://api.genius.com/"

mainurl = "https://genius.com/"
headers = {"Authorization" : "Bearer "+ genius_access_token}

global maindict

#List of 500 most popular artists sorted from most popular to least popular. List from Billboard
#As top artists discogrpahy was already searched, I deleteed their name from the list
#These artists were the last to be search and hence havent been deleted
listofartists = [
    "Tyler Childers",
    "Miky Woodz",
    "Yelawolf",
    "6LACK",
    "Hillsong UNITED",
    "Little Big Town",
    "AJR",
    "Kelsea Ballerini",
    "Dierks Bentley",
    "Breaking Benjamin",
    "Conan Gray",
    "Oxxxymiron",
    "Chelsea Cutler",
    "Kygo & Chelsea Cutler",
    "Flipp Dinero",
    "Key Glock",
    "Guns N’ Roses",
    "Desiigner",
    "Creedence Clearwater Revival",
    "Why Don’t We",
    "Pitbull & Kesha",
    "MiixedLoveVEVO",
    "Dan Bull",
    "Cassidy",
    "Trev Rich",
    "Novelist",
    "SMACKTOWN",
    "DINAS",
    "Pharaoh",
    "Big Time Rush",
    "Russ (UK)",
    "William Singe",
    "K CAMP",
    "Upchurch",
    "SZA",
    "Alan Jackson",
    "Daddy Yankee",
    "Avenged Sevenfold",
    "Cody Johnson",
    "Skillet",
    "Sivas",
    "Gims",
    "Mumford & Sons",
    "Garth Brooks",
    "Romeo Santos",
    "Enya",
    "Brantley Gilbert",
    "Pusha T",
    "Lee Brice",
    "System of a Down",
    "Ali Gatie",
    "J Balvin",
    "TOKYO’S REVENGE",
    "Tech N9ne",
    "CUCO",
    "Brooks & Dunn",
    "Chris Lane",
    "Gabby Barrett",
    "Luh Kel",
    "Riley Green",
    "N.W.A",
    "Dr. Dre",
    "Hall & Oates",
    "Nelly Furtado",
    "Fuerza Regida",
    "James TW",
    "James Taylor",
    "Cole Swindell",
    "Calboy",
    "Van Halen",
    "Sleepy John Estes",
    "Jackie Greene",
    "Joey Bada$$",
    "Cassie",
    "Curren$y",
    "OBLADAET",
    "DigDat",
    "83 Babies",
    "Higher Brothers",
    "ScHoolboy Q",
    "Young Maylay",
    "Maluma",
    "Bedoes",
    "Sus Scrofa",
    "CashMoneyAP",
    "No Rome",
    "Cashmo",
    "Casting Crowns",
    "Dean Lewis",
    "Mert",
    "A$AP Ferg",
    "Jon Bon Jovi",
    "Olivia Rodrigo",
    "Surfaces",
    "Quinn XCII",
    "Joyner Lucas",
    "Ne-Yo",
    "KYLE",
    "Kyle Massey",
    "Yung Gravy",
    "Ava Max",
    "Norah Jones",
    "DaniLeigh",
    "ODESZA",
    "Hayden James",
    "Jordan Davis",
    "James Arthur",
    "MercyMe",
    "Marvin Gaye",
    "B.o.B",
    "The Strokes",
    "Bryce Vine",
    "JP Saxe",
    "Destiny’s Child",
    "Vance Joy",
    "Godsmack",
    "Alice in Chains",
    "Toby Keith",
    "Mary J. Blige",
    "Andy Grammer",
    "Phil Collins",
    "Mitchell Tenpenny",
    "Bob Seger",
    "Atmosphere",
    "Freddie Dredd",
    "Billy Currington",
    "Mötley Crüe",
    "Grateful Dead",
    "Jason Mraz",
    "​for KING & COUNTRY",
    "YK Osiris",
    "Ruel",
    "Ruelle",
    "Ernia",
    "Lupe Fiasco",
    "The Black Eyed Peas",
    "will.i.am",
    "A Day To Remember",
    "Jeremy Zucker",
    "BONES",
    "24kGoldn",
    "Lisa Loeb",
    "Yungeen Ace",
    "Earth, Wind & Fire",
    "Matthew Wilder",
    "Chase Rice",
    "Cavetown",
    "GONE.Fludd",
    "Julia Michaels",
    "Scorpinox",
    "Miguel de Unamuno",
    "Sene",
    "Noam Chomsky",
    "Jeff Le Nerf",
    "President Jimmy Carter",
    "Zachary Taylor",
    "Yung Pinch",
    "Christian Nodal",
    "Matchbox Twenty",
    "Eric Bellinger",
    "TobyMac",
    "Lord Huron",
    "Theory",
    "Vitamin String Quartet",
    "Two Friends",
    "Fitz and The Tantrums",
    "T3R Elemento",
    "Calibre 50",
    "Chris Tomlin",
    "The Doors",
    "Mac DeMarco",
    "Brad Paisley",
    "RAPTORS",
    "509-E",
    "Tede",
    "Genius Brasil",
    "3 Doors Down",
    "I Prevail",
    "Seether",
    "IBri",
    "Tulisa",
    "Mark Knopfler",
    "James Bay",
    "Sadek",
    "Sade",
    "Justin Moore",
    "​gnash",
    "T-Wayne",
    "Russ & BIA",
    "Young Stunners",
    "​Biosphere",
    "Jeff Russo",
    "John Denver",
    "Mangaturtle",
    "Ant Saunders",
    "Marca MP",
    "Bring Me The Horizon",
    "Christina Perri",
    "Hank Williams Jr.",
    "Calum Scott",
    "070 Shake",
    "Rage Against the Machine",
    "Dixie Chicks",
    "The Head and the Heart",
    "Russell Dickerson",
    "Bon Iver",
    "Vampire Weekend",
    "Bethel Music",
    "Brent Faiyaz",
    "Electric Light Orchestra",
    "Papa Roach",
    "Snoh Aalegra",
    "Pentatonix",
    "Maggie Rogers",
    "Anuel AA",
    "Dominic Fike",
    "Hollywood Undead",
    "ABBA",
    "Bas",
    "PnB Rock",
    "Demi Lovato",
    "Jacquees",
    "Alicia Keys",
    "Shinedown",
    "Slipknot",
    "Hozier",
    "50 Cent",
    "Diplo",
    "Fabolous",
    "Justin Timberlake",
    "Calvin Harris",
    "YFN Lucci",
    "Chris Young",
    "Mariah Carey",
    "Three Days Grace",
    "Elvis Presley",
    "My Chemical Romance",
    "Keith Urban",
    "Miguel",
    "Johnny Cash",
    "6lack",
    "Idina Menzel",
    "Disturbed",
    "Jeremih",
    "Journey",
    "John Legend",
    "Daniel Caesar",
    "Tool",
    "Weezer",
    "Metro Boomin",
    "Guns N' Roses",
    "G Herbo",
    "French Montana",
    "Marshmello",
    "Avicii",
    "T.I.",
    "Lorde",
    "Kesha",
    "Jeezy",
    "Metro Boomin",
    "Guns N' Roses",
    "G Herbo",
    "French Montana",
    "Marshmello",
    "Baby Keem",
    "Avicii",
    "T.I.",
    "Lorde",
    "Bebe Rexha",
    "Kesha",
    "Jeezy",
    "Rascal Flatts",
    "Paramore",
    "Pearl Jam",
    "Lil Yachty",
    "Meghan Trainor",
    "Niall Horan",
    "Rush",
    "Aerosmith",
    "Cage The Elephant",
    "6ix9ine",
    "Chief Keef",
    "Sza",
    "Michael Bublé",
    "Lynyrd Skynyrd",
    "The Game",
    "Sia",
    "Young Dolph",
    "Alessia Cara",
    "OutKast",
    "Sublime",
    "Aventura",
    "Blueface",
    "Charlie Puth",
    "Britney Spears",
    "Gorillaz",
    "Shakira",
    "T-Pain",
    "Kelly Clarkson",
    "System Of A Down",
    "Rae Sremmurd",
    "Radiohead",
    "Tokyo’s Revenge",
    "Clairo",
    "Tech N9NE",
    "Pitbull",
    "Foo Fighters",
    "Stevie Wonder",
    "Aminé",
    "Dr. Dre",
    "Bob Marley & The Wailers",
    "Jason Derulo",
    "Van Morrison",
    "Korn",
    "Nelly",
    "The Killers",
    "Yo Gotti",
    "Arctic Monkeys",
    "Bruce Springsteen",
    "Noah Cyrus",
    "Jake Owen",
    "Flo Rida",
    "Schoolboy Q",
    "Young M.A",
    "The Beach Boys",
    "Cody Jinks",
    "Ty Dolla $ign",
    "City Girls",
    "Whitney Houston",
    "Fetty Wap",
    "Bob Dylan",
    "Train",
    "Pinkfong",
    "Comethazine",
    "U2",
    "David Bowie",
    "ASAP Ferg",
    "Bon Jovi",
    "Smokepurpp",
    "Ozzy Osbourne",
    "The Neighbourhood",
    "Odesza",
    "Nickelback",
    "Ciara",
    "Jon Bellion",
    "YBN Cordae",
    "Lil Keed",
    "Foster the People",
    "David Guetta",
    "Saweetie",
    "Def Leppard",
    "Snoop Dogg",
    "Destiny's Child",
    "Major Lazer",
    "Daft Punk",
    "Akon",
    "The Black Keys",
    "Yk Osiris",
    "Avril Lavigne",
    "Madonna",
    "Black Eyed Peas",
    "R. Kelly",
    "Kid Rock",
    "24kgoldn",
    "Offset",
    "Bee Gees",
    "Tove Lo",
    "Earth Wind & Fire",
    "Ice Cube",
    "Beastie Boys",
    "Mac Demarco",
    "Denzel Curry",
    "Florence + The Machine",
    "Willie Nelson",
    "Dave Matthews Band",
    "Nas",
    "Ellie Goulding",
    "ZAYN",
    "Anderson .Paak",
    "Rage Against The Machine"
]

def Loader():
    '''loads in masterfile'''
    try:
        global maindict
        maindict = json.load(open("masterfile.txt"))
    except:
        pass

def JSONGrabber(artistname):
    '''Grabs URL containing 20 songs off of a webpage of an artist'''
    try:
        encodedname = urllib.parse.quote(artistname)
        r = requests.get(base_url + "search?q=" + encodedname, headers=headers)
        maintext = r.json()
        artistID = maintext['response']['hits'][0]['result']['primary_artist']['api_path']
        MainURL = (base_url+artistID[1:]+"/songs?sort=popularity&per_page=20&page=")
        return MainURL
    except:
        print("{} FAILED ".format(artistname))

def URLGetter(MainURL):
    '''Gets URLs for each song, and sends them to LyricsGrabber'''
    for num in range(5):
        num = num+1
        r = requests.get(str(MainURL)+str(num),headers=headers)
        mainjson = r.json()
        for song in mainjson['response']['songs']:
            try:
                url = song['url']
                artistname = song['primary_artist']['name']
                songname = song['title']
                if songname not in maindict[artistname].keys():
                    LyricsGrabber(url,artistname,songname)
                else:
                    pass
            except:
                pass

def LyricsGrabber(url,artistname,songname):
    '''gets lyrics for a song, given the URL'''
    r = requests.get(url)
    html = BeautifulSoup(r.text, "html.parser")
    [h.extract() for h in html('script')]
    lyrics = html.find('div', class_='lyrics').get_text()
    if artistname not in maindict.keys():
        maindict[artistname] = {}
    maindict[artistname][songname] = lyrics

def Saver():
    '''Saves masterfile'''
    json.dump(maindict,open("masterfile.txt",'w'))

if __name__ == "__main__":
    Loader()
    for artistname in listofartists:
        try:
            MainURL = JSONGrabber(artistname)
            URLGetter(MainURL)
        except:
            pass
        Saver()
        print("{} is done. Actually take them off the list".format(artistname))
        time.sleep(1)
    print("DONE FOR GOOD")




